# Generated by Django 4.2.4 on 2023-09-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_stack', '0005_question_stack_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Mathematics', max_length=100),
        ),
    ]
