# Generated by Django 4.2.4 on 2023-09-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_stack', '0006_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='none', max_length=1000),
        ),
    ]
