# Generated by Django 4.2.4 on 2023-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_stack', '0007_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offline_schedule',
            field=models.TextField(default='json here', max_length=100000),
        ),
    ]
