# Generated by Django 4.2.4 on 2023-09-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_stack', '0008_course_offline_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='monitor',
            field=models.TextField(default='none', max_length=1000),
        ),
    ]
